#!/usr/bin/env python3

import argparse
import pandas as pd
import csv


def convert_csv_eventlog(inp, out):
    events = pd.read_csv(inp)

    mri_triggers = events[(events['event'] == 'MRI_Trigger') &
                          (events['info'] == 'Received')]

    start_time_s = mri_triggers.iloc[0].time_s

    events['time_s'] = events['time_s'] - start_time_s
    events['record_time_s'] = events['record_time_s'] - start_time_s

    events.to_csv(out, sep='\t', quoting=csv.QUOTE_NONE, index=False,
                  na_rep='n/a', float_format='%0.4f')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Converts CSV eventlogs to TSV event logs with timing '
                    'relative to first MRI trigger.')

    parser.add_argument('-i', type=str, help='Input CSV eventlog')
    parser.add_argument('-o', type=str, help='Output TSV eventlog')

    args = parser.parse_args()

    convert_csv_eventlog(args.i, args.o)
