#PBS -lwalltime=72:00:00  
#PBS -lnodes=1:ppn=16
#PBS -S /bin/bash

n=`wc -l < $PBS_NODEFILE`
echo start of job in directory $PBS_O_WORKDIR
echo number of nodes is $n
echo the allocated nodes are:
cat $PBS_NODEFILE

module load eb
module load freesurfer
module load fsl/5.08
module load afni

source ~/.bash_profile 
source ~/.bashrc

export FSLOUTPUTTYPE=NIFTI_GZ # is this not the default?

cd ~/NHP-BIDS

./code/bids_minimal_processing.py --csv ./csv/minproc/Danny_minproc_20181213.csv  |& tee ./logs/minproc/log-minproc-danny-20181213.txt
./code/resample_isotropic_workflow.py --csv ./csv/preproc/Danny_preproc_20181213.csv  |& tee ./logs/resample/sub-danny/log-resample_iso-danny-20181213.txt
./code/resample_hires_isotropic_workflow.py --csv ./csv/preproc/Danny_preproc_20181213.csv  |& tee ./logs/resample/sub-danny/log-resample_iso-hires--danny-20181213.txt

./code/preprocessing_workflow_danny.py --csv ./csv/preproc/Danny_preproc_20181213.csv  |& tee ./logs/preproc/sub-danny/log-preproc-danny-20181213_modelfit.txt

echo "Job $PBS_JOBID ended at `date`." | mail $USER -s "Job $PBS_JOBID ended"